### ISSUE TITLE
tags from 2018 in 2016 data summary

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#10]
in the fish2016_sum.csv file. could be due to non-unique tag_short code?

**Comment by avastano** [comment]
Let's discuss, but could this be from fish that were tagged in 2016 and detected in 2018?

**Comment by mikeallen-eco** [comment]
These are likely due to tags used to test antennas then put into a fish. Mike make code to exclude pings that predate tagging events. Make a list of tags where this occurred.

**Comment by mikeallen-eco** [comment]
Done. All excluded pings are listed in the "output/pings_predate_tagging.csv" file.
