### ISSUE TITLE
What's up with file: "21 05_29_14_A2_for real.TXT"

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#11]
It has the same name as another file, but with the ending "for real". Should both be included? 
[1] "20 05_29_14_A2.TXT"
[1] "21 05_29_14_A2_for real.TXT"

**Comment by avastano** [comment]
Yes, both should be included. It appears  "20 05_29_14_A2.TXT" is actually from field A1, and  "21 05_29_14_A2_for real.TXT" was really from field A2. I have noted this in the key I just sent over, and I think that solves the issue.

**Comment by mikeallen-eco** [comment]
OK, both are included. And the key solved the naming issue.
