### ISSUE TITLE
file 06_05_14.TXT has no D/E/B code prefixes

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#12]
It also seemingly contains data from 2011 and 2012? Excluded this file for now.

**Comment by avastano** [comment]
Yes, that is a redundant file from 2012. We were likely putting our spare receiver into service and during the data upload it pulled all the old data from 2012. I see those reads in the appropriate, raw 2012 file, so fine to exclude in 2014.

**Comment by mikeallen-eco** [comment]
OK!
