### ISSUE TITLE
file 05_15_14 DownStream.TXT

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#13]
This file lacks a column for antenna name (e.g., A1, A2, etc). Excluding for now.

**Comment by avastano** [comment]
Should be included and all entires changed to updated Antenna number A1 (Downstream entrance).
The other 5_15_14.txt file has some data from both antennas (up and downstream), but that day we were likely running two receivers.

**Comment by mikeallen-eco** [comment]
Done. Now the file is included and antenna number is "A1"
