### ISSUE TITLE
2013 data types

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#16]
What is the difference between the pings labeled "A" and "R"? How do we tell which rows are good data? (There is no D, B, etc. prefix in the 2013 files.)

**Comment by avastano** [comment]
Not sure. Let's take a look and if we can't figure it out, I can reach out to their tech support.

**Comment by mikeallen-eco** [comment]
Not sure what they mean, but "A" and "R" were used to pull the data from the non-data in the text files. It seems there is one record with a "W". Anthony is looking into what they mean.

**Comment by mikeallen-eco** [comment]
A is some kind of registered animal tag; R is non ICAR tag; W = writable. We now include the lone W ping.
