### ISSUE TITLE
uneven distribution of pings by date, 2013

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#18]
![image](https://user-images.githubusercontent.com/32096773/147288844-b328a6be-82ec-4f52-a19a-e9aefabc7c06.png)

**Comment by avastano** [comment]
Antenna performance issues? Let's discuss and take a look. Could just be marker tag frequency, or a non-functioning antenna. I like these plots though!

**Comment by mikeallen-eco** [comment]
Closing this as we are already planning to plot pings/day/antenna as described in a different issue.
