### ISSUE TITLE
maybe a fish

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#19]
This one was dropped but might be a fish:
06/25/2013 08:28:09.04  00:00:00.52 A 00000 0 900 226000011001 A1    7   547

Is it worth coding in to include?

**Comment by avastano** [comment]
Does not appear to be a fish, but why dropped?

**Comment by mikeallen-eco** [comment]
Never mind. Turns out it was not dropped!
