### ISSUE TITLE
two 2030 pings in 2012 data

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#20]
I excluded those.
There are also several pings from June 2011 which I left in.

**Comment by mikeallen-eco** [comment]
both 2030 tags were 0000_0000000174764773

**Comment by avastano** [comment]
Marker tag detections. Date got corrupt. Can we just edt to date above/below?

**Comment by mikeallen-eco** [comment]
OK, but what to do about the 154 pings from 2011 in the 2012 files? 
They are from receiver files 04_05_12.TXT, 04_18_12.TXT (and maybe others?)
