### ISSUE TITLE
negative "attraction days" (i.e., pings that predate tagging time)

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#22]
Many in 2012, for example:
tag 000010998  Alewife  2013-05-23 13:00:00 pinged in 2012
tag 000011050  River Herring  2018-04-24 12:25:00 pinged in 2012
tag 000010987  Blueback Herring  2013-05-01 10:00:00 pinged in 2012
tag 000011082  Alewife  2013-05-17 14:00:00 pinged in 2012
tag 166982662  Blueback Herring 2012-04-30 13:00:00 pinged 2012-04-07 15:11:36.21

**Comment by avastano** [comment]
Not sure what's going on here... I'll do some looking, but let's discuss.

**Comment by mikeallen-eco** [comment]
Not just in 2012. See fish_sum.csv.

**Comment by mikeallen-eco** [comment]
Mike will make code to exclude pings that predate the tagging. These were likely just tests of the tag.

**Comment by mikeallen-eco** [comment]
Done. All excluded pings are listed in the file "output/pings_predate_tagging.csv".
