### ISSUE TITLE
Mike tally fish counted night vs. day

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#27]

**Comment by mikeallen-eco** [comment]
Here is what I came up with from the video count data, defining "daylight" as 7am-7pm (roughly correct). See below or in the "proportion_counts_in_daytime.csv" file in the 'output' folder.

daytime = 1 is daylight count, 0 = nighttime count.
pday = proportion of total for that year. 

species	                year	  daytime	 n	 pday
American Shad	2013	0	87	0.281553398
American Shad	2013	1	222	0.718446602
American Shad	2014	0	28	0.100358423
American Shad	2014	1	251	0.899641577
American Shad	2015	0	15	0.12195122
American Shad	2015	1	108	0.87804878
American Shad	2016	0	9	0.191489362
American Shad	2016	1	38	0.808510638
American Shad	2017	0	156	0.129246065
American Shad	2017	1	1051	0.870753935
American Shad	2018	0	55	0.122494432
American Shad	2018	1	394	0.877505568
American Shad	2019	0	7	0.071428571
American Shad	2019	1	91	0.928571429
River Herring spp.	2013	0	9	0.219512195
River Herring spp.	2013	1	32	0.780487805
River Herring spp.	2014	0	19	0.158333333
River Herring spp.	2014	1	101	0.841666667
River Herring spp.	2015	0	1	0.1
River Herring spp.	2015	1	9	0.9
River Herring spp.	2016	0	22	0.372881356
River Herring spp.	2016	1	37	0.627118644
River Herring spp.	2017	0	22	0.082397004
River Herring spp.	2017	1	245	0.917602996
River Herring spp.	2018	0	55	0.264423077
River Herring spp.	2018	1	153	0.735576923
River Herring spp.	2019	0	6	0.222222222
River Herring spp.	2019	1	21	0.777777778

**Comment by mikeallen-eco** [comment]
Those numbers are based on the video counts. Were you looking for a count of the fish antenna detections in the night vs. the day instead?

**Comment by avastano** [comment]
Please make histogram of counts by hour and inspect 2013 by hour given no infrared that year.

**Comment by mikeallen-eco** [comment]
This plot is also saved in the figures/ folder. 
![fish_counts_by_hour_histograms](https://user-images.githubusercontent.com/32096773/160675043-e10f91b5-cea6-4daf-b94a-8268e4cac7c4.png)

**Comment by avastano** [comment]
Thanks. Interesting... either many of these species don't pass at night, or the system doesn't work very well to see these species in the dark. We'll ask Olaf, but perhaps not worth correcting for lack of night video in 2013 (or prior years) and perhaps focus on number of days video was active?

**Comment by mikeallen-eco** [comment]
Mike needs to 1) convert "hour" to time relative to sunrise/sunset, 2) shade times after sunset gray.

**Comment by mikeallen-eco** [comment]
Done
