### ISSUE TITLE
herring 166994725 timing issue

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#28]
For herring 166994725: first ping at A4 is 30 seconds before last ping at A1. Is this possible? Check antenna naming?

**Comment by avastano** [comment]
This "fish" most likely was not a tagged fish, but someone testing a tag at the antennas and the same day inserted into a fish. It was not counted as a tagged fish in that year's annual report and someone (Orion/Olaf/Andrew) wrote "These two hits are from when I tested the antennas on May 3rd", so we can omit it as a test tag for any detections on that day.

**Comment by mikeallen-eco** [comment]
@mikeallen-eco will remove this "fish"

**Comment by mikeallen-eco** [comment]
removed the erroneous pings (in compile_pings2012.R) which in turn removed the fish from staging time calculations, etc.
