### ISSUE TITLE
Video count data for Anthony to check

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#29]
species year    n
1       American Shad 1996   48
2       American Shad 1997   76
3       American Shad 1998  149
4       American Shad 1999  582
5       American Shad 2000   NA
6       American Shad 2001  717
7       American Shad 2002 1114
8       American Shad 2003  362
9       American Shad 2004   NA
10      American Shad 2005   13
11      American Shad 2013  309
12      American Shad 2014  279
13      American Shad 2015  123
14      American Shad 2016   47
15      American Shad 2017 1207
16      American Shad 2018  449
17      American Shad 2019   98
18 River Herring spp. 1996    0
19 River Herring spp. 1997  117
20 River Herring spp. 1998    9
21 River Herring spp. 1999  114
22 River Herring spp. 2000   NA
23 River Herring spp. 2001   61
24 River Herring spp. 2002   17
25 River Herring spp. 2003   12
26 River Herring spp. 2004   NA
27 River Herring spp. 2005    0
28 River Herring spp. 2013   41
29 River Herring spp. 2014  120
30 River Herring spp. 2015   10
31 River Herring spp. 2016   59
32 River Herring spp. 2017  267
33 River Herring spp. 2018  208
34 River Herring spp. 2019   27

**Comment by avastano** [comment]
2018 shad differs from our shared summary chart (I have 473 vs. 449 above). 
2019 shad differs (chart: 96 vs. 98 above)
2016 herring differs (chart: 115 vs. 59 above)
2017 herring differs (chart: 271 vs. 267 above)
2018 herring differs (chart: 109 vs. 208 above)

I now have 2020 & 2021 numbers for both species. I will review these numbers, compare, and provide updated video datafile to you.

**Comment by avastano** [comment]
Final, updated data file sent last week (with numbers somewhat different than above).
