### ISSUE TITLE
Mike make stairstep figure for antenna passage

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#30]
proportion of tagged fish pinging A1 -> A2 -> A3 -> A4

**Comment by avastano** [comment]
Thanks! I'm wondering if it's worth combining them into one figure or if this is clearer. Will think about it, but certainly a striking difference. It's pretty clear to me that reaching the ladder entrance is the biggest "hurdle". Could be fallback, or they just can't find it...

**Comment by mikeallen-eco** [comment]
Added figure to supplemental material.
