### ISSUE TITLE
Unusually long transit time (very unusual)

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#31]
There is a shad (tag: 000008986) with a transit time (max A1 time -> max A4 time) of 16.5 days. The next highest value is ~1day with a median of 0.009. Is this correct?

**Comment by avastano** [comment]
This was an interesting fish. It passed sucessfully on 5/13 (going through all antennas), then it came back to A4 16 days later (which is what is being calculated above), hung around, and returned again a few hours later on the next day. I'm coming up manually with a transit time of 1:13:23 (Max A1 time -> Min A4 time), and I think that's what we should report for this fish's transit time.

I noticed you're calculating transit as A1 Max to A4 Max. In the annual reports, we defined transit time as "The amount of time between the last detection at the downstream antenna (A1) and the first detection at the upstream antenna (A4). This defines the amount of time it takes a fish to traverse the fish ladder.", suggesting it should be max A1 to min A4. This also matches a recent paper that seeks to standardize these metrics in a number of ways, but defines transit time as "time lapse between the last read of the downstream antenna and the first read of the upstream antenna (Castro-Santos et al., 1996)" (Bravo-Cordoba et al. 2021). 

Could you please adjust the way that metric is calculated and update the transit times accordingly?

**Comment by mikeallen-eco** [comment]
@mikeallen-eco will update the way transit time is calculated

**Comment by mikeallen-eco** [comment]
updated
