### ISSUE TITLE
make look up table for receivers in each year

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#5]
This might help:
Key: 
Year: Updated A# = File Name + A#

2012: A1=A2, A4=A1, this year only one receiver box was run, so no up/down files.
2013: A1=A2, A4=A1, this year only one receiver box was run, so no up/down files.
2014: A1= A2, A4=A1, this year we used one receiver box for the most part, so let's assume A1= A2, A4=A1 for now, but then it switched to two: if latter file name has A1, assume it's the receiver for A1 (update to A4), if file name has A2, assume it's updated antenna A1.
2015: A1= Down A1, A2= Down A3, A3=Up A3, A4= Up A1
2016: A1=Down A1, A2= Down A3, A3= Up A1 (but sometimes A3), A4= Up A3 (but sometimes A1)
2017-2019: Antennas should be what they say. :)

**Comment by mikeallen-eco** [comment]
antennas in 2016 were assigned names A1 through A4 based on the rules above, but the exceptions (in the parentheses) still need to be corrected

**Comment by mikeallen-eco** [comment]
antennas in 2015 were assigned names A1 through A4 based on the rules above

**Comment by avastano** [comment]
New key emailed this evening.

2015/2016:  Let's see what the fish and tag data look like based on the updated key, I'm hoping there are not too many exceptions from 2016, and if there are I can look at those file by file again.
