### ISSUE TITLE
calculate days array is "operational"

### ISSUE THREAD

**Issue by mikeallen-eco** [mikeallen-eco/fish_pass#6]
So I think the number of days within the range that had pings from a marker tag per antenna (or some fraction of the day)? We would use this information to say the array was operational for X percent (x days) of the field season (X/XX/XXXX-X/XX/XXXX).

**Comment by avastano** [comment]
Correct. Let's gather the field season days from the tag data for now, but I can generate a list of start and end days for each season. 

In terms of determining operational days, I think this may be easier visually, at least at first, but basically we want to see if there are any gaps in marker tag detections beyond the set interval (something like 15 minutes). Then we would say if it's not operational for an extended period of time that day needs to be reported as such in some way. Issue is we work on the antennas twice weekly, so there will be regular down time there. Perhaps we should discuss when we meet next?

**Comment by mikeallen-eco** [comment]
Count pings per day per antenna and make diagnostic plot.

**Comment by mikeallen-eco** [comment]
Made these diagnostic plots (saved in "/Figures").

**Comment by mikeallen-eco** [comment]
What is a good threshold value to count as "present"? there are quite a few that seem to have a steady amount that is less than 96 (more like 50-80 something). Also can you remind me of the start and stop dates for the season: first tagging date until ?

**Comment by avastano** [comment]
Good question. 96 is a full day (every 15 min), but sometimes the marker tags are what's not working, and not the antennas (so the array is working fine). Perhaps we could see what 100%, 90% and 75% thresholds look like? So 80 would be 83%, and count as fine for that day. 

The start and stop dates would be first tagging day until the last day the array is active (generally last few days in June/ July 1st, with some exceptions.

**Comment by mikeallen-eco** [comment]
I created a "antenna_days_active.csv" file in the output folder that should help.
